``0-add_integer`` Module
===================

``add_integer()`` computes the sum of two numbers.

Import Module:
	>>> add_integer = __import__('0-add_integer').add_integer

two integers:
	>>> add_integer(2, 3)
	5

two floats:
	>>> add_integer(2.1, 3.2)
	5

a is int and b is float:
	>>> add_integer(2, 3.5)
	5

a is float and b is int:
	>>> add_integer(2.5, 3)
	5

one positive one negative:
	>>> add_integer(-2, 3)
	1

	>>> add_integer(-2.3, 3)
	1

	>>> add_integer(2, -3)
	-1

	>>> add_integer(2, -3.5)
	-1

two negative numbers:
	>>> add_integer(-2, -3)
	-5

	>>> add_integer(-2.1, -3.5)
	-5

two large numbers:
	>>> add_integer(20000000, 30000000)
	50000000

only one argument:
	>>> add_integer(2)
	100

one is a string:
	>>> add_integer('a', 3)
	Traceback (most recent call last):
		...
	TypeError: a must be an integer

	>>> add_integer(2, 'a')
	Traceback (most recent call last):
		...
	TypeError: b must be an integer

one is a list:
        >>> add_integer([1, 2], 3)
        Traceback (most recent call last):
                ...
        TypeError: a must be an integer

        >>> add_integer(2, [1, 2])
        Traceback (most recent call last):
                ...
        TypeError: b must be an integer

one is a tuple:
        >>> add_integer((1, 2), 3)
        Traceback (most recent call last):
                ...
        TypeError: a must be an integer

        >>> add_integer(2, (1, 2))
        Traceback (most recent call last):
                ...
        TypeError: b must be an integer

one is a set:
        >>> add_integer({1, 2}, 3)
        Traceback (most recent call last):
                ...
        TypeError: a must be an integer

        >>> add_integer(2, {1, 2})
        Traceback (most recent call last):
                ...
        TypeError: b must be an integer

one argument missing:
        >>> add_integer()
        Traceback (most recent call last):
                ...
        TypeError: add_integer() missing 1 required positional argument: 'a'

more than 2 arguments passed:
	>>> add_integer(2, 3, 4)
	Traceback (most recent call last):
		...
	TypeError: add_integer() takes from 1 to 2 positional arguments but 3 were given

one is None:
	>>> add_integer(None, 3)
	Traceback (most recent call last):
		...
	TypeError: a must be an integer

	>>> add_integer(2, None)
	Traceback (most recent call last):
		...
	TypeError: b must be an integer
